let DATA;fetch('../data/unica-dashboard.json',{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error('HTTP '+r.status);return r.json()}).then(json=>{DATA=json;const order=['04-16','05-01','05-16','06-01','06-16','07-01','07-16','08-01','08-16','09-01','09-16','10-01','10-16','11-01','11-16','12-01','12-16','01-01','01-16','02-01','02-16','03-01','03-16','04-01'];const metricMap=Object.fromEntries(DATA.metrics.map(m=>[m.id,m]));
const defs=[
 {group:'中南部乙醇总量',items:[['south_central_anhydrous_biweekly','中南部无水乙醇双周产量'],['south_central_anhydrous_accumulated','中南部无水乙醇累计产量'],['south_central_hydrous_biweekly','中南部含水乙醇双周产量'],['south_central_hydrous_accumulated','中南部含水乙醇累计产量'],['south_central_total_biweekly','中南部乙醇合计双周产量'],['south_central_total_accumulated','中南部乙醇合计累计产量']]},
 {group:'玉米乙醇',items:[['south_central_corn_anhydrous_biweekly','中南部玉米无水乙醇双周产量'],['south_central_corn_anhydrous_accumulated','中南部玉米无水乙醇累计产量'],['south_central_corn_hydrous_biweekly','中南部玉米含水乙醇双周产量'],['south_central_corn_hydrous_accumulated','中南部玉米含水乙醇累计产量'],['south_central_corn_total_biweekly','中南部玉米乙醇合计双周产量'],['south_central_corn_total_accumulated','中南部玉米乙醇合计累计产量']]},
 {group:'甘蔗乙醇',items:[['south_central_cane_anhydrous_biweekly','中南部甘蔗无水乙醇双周产量'],['south_central_cane_anhydrous_accumulated','中南部甘蔗无水乙醇累计产量'],['south_central_cane_hydrous_biweekly','中南部甘蔗含水乙醇双周产量'],['south_central_cane_hydrous_accumulated','中南部甘蔗含水乙醇累计产量'],['south_central_cane_total_biweekly','中南部甘蔗乙醇合计双周产量'],['south_central_cane_total_accumulated','中南部甘蔗乙醇合计累计产量']]}
];const titleMap=Object.fromEntries(defs.flatMap(g=>g.items));const allDefs=defs.flatMap(g=>g.items.map(x=>({id:x[0],title:x[1],group:g.group}))).filter(x=>metricMap[x.id]);const fmt=n=>n==null?'—':Math.round(n).toLocaleString('zh-CN');const fmtMillion=n=>n==null?'—':Math.round(n/1000).toLocaleString('zh-CN');const fmtDb=n=>n==null?'—':(n/1000).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});const pct=n=>n==null?'—':(n*100).toFixed(1)+'%';const shortSeason=s=>s.slice(2,4)+'/'+s.slice(7,9);const byOrder=(a,b)=>order.indexOf(a.period)-order.indexOf(b.period);const seasons=m=>[...new Set(m.rows.map(r=>r.season))].sort();
document.getElementById('meta').textContent=`数据截至 ${DATA.meta.position_date||'未知'}｜报告发布 ${DATA.meta.publication_date||'未知'}｜最近更新 ${DATA.meta.generated_at.slice(0,19).replace('T',' ')}`;
function latest(m){const ss=seasons(m),s=ss.at(-1);return m.rows.filter(r=>r.season===s).sort(byOrder).at(-1)}
const cardIds=['south_central_total_biweekly','south_central_corn_total_biweekly','south_central_cane_total_biweekly','south_central_total_accumulated','south_central_corn_total_accumulated','south_central_cane_total_accumulated'];document.getElementById('asofNote').textContent='注：以上指标统一为 '+shortSeason(seasons(metricMap[cardIds[0]]).at(-1))+' 榨季 '+latest(metricMap[cardIds[0]]).period+' 数据。';document.getElementById('cards').innerHTML=cardIds.map(id=>metricMap[id]).filter(Boolean).map(m=>{const r=latest(m),ss=seasons(m),same=m.rows.filter(x=>x.season===r.season).sort(byOrder),prior=same.at(-2),report=prior?(r.value/prior.value-1):null,prev=m.rows.find(x=>x.season===ss.at(-2)&&x.period===r.period),yoy=prev&&prev.value?r.value/prev.value-1:r.yoy_pct;return `<div class=card><div class=name>${titleMap[m.id]||m.name}</div><div class=value>${fmtMillion(r.value)} <span style="font-size:12px;font-weight:500;color:#607487">百万升</span></div><div class=small>较上次报告：${pct(report)}<br>同比：<span class="${yoy>=0?'up':'down'}">${pct(yoy)}</span>｜分位 ${pct(r.percentile)}｜去趋势 ${pct(r.detrended_percentile)}</div></div>`}).join('');
const colors=['#5c7cfa','#2f9e44','#f59f00','#845ef7','#d6336c','#15aabf','#e8590c'];
function concise(m){const ss=seasons(m),latestS=ss.at(-1),prevS=ss.at(-2),hist=ss.filter(s=>s!==latestS),n=hist.length,x=order;const hBy=x.map(p=>hist.map(s=>m.rows.find(r=>r.season===s&&r.period===p)?.value).filter(v=>v!=null));const lo=hBy.map(a=>a.length?Math.min(...a)/1000:null),hi=hBy.map(a=>a.length?Math.max(...a)/1000:null),avg=hBy.map(a=>a.length?a.reduce((x,y)=>x+y,0)/a.length/1000:null);const rr=s=>m.rows.filter(r=>r.season===s).sort(byOrder);const p=rr(prevS),l=rr(latestS);return [{x,y:lo,name:`${n}年最小值`,type:'scatter',mode:'lines',line:{color:'#a9a9a9',width:1},hovertemplate:`${n}年最小值 %{y:,.0f}<extra></extra>`},{x,y:hi,name:`${n}年最大值`,type:'scatter',mode:'lines',fill:'tonexty',fillcolor:'rgba(128,128,128,.42)',line:{color:'#a9a9a9',width:1},hovertemplate:`${n}年最大值 %{y:,.0f}<extra></extra>`},{x,y:avg,name:`${n}年均值`,type:'scatter',mode:'lines',line:{color:'#6c757d',dash:'dash',width:2},hovertemplate:`${n}年均值 %{y:,.0f}<extra></extra>`},{x:p.map(r=>r.period),y:p.map(r=>r.value/1000),name:shortSeason(prevS),type:'scatter',mode:'lines',line:{color:'#111',width:2.2},hovertemplate:`${shortSeason(prevS)} %{x}<br>%{y:,.0f}<extra></extra>`},{x:l.map(r=>r.period),y:l.map(r=>r.value/1000),name:shortSeason(latestS),type:'scatter',mode:'lines+markers',marker:{size:6,color:'#d00000'},line:{color:'#d00000',width:2.4},hovertemplate:`${shortSeason(latestS)} %{x}<br>%{y:,.0f}<extra></extra>`},{x:l.map(r=>r.period),y:l.map(r=>r.yoy_pct),name:'同比',type:'scatter',mode:'lines',yaxis:'y2',line:{color:'#ff3b30',width:2,dash:'dot'},hovertemplate:'同比 %{y:.1%}<extra></extra>'}]}
function seasonal(m){const ss=seasons(m);return ss.map((s,i)=>{const rr=m.rows.filter(r=>r.season===s).sort(byOrder);return{x:rr.map(r=>r.period),y:rr.map(r=>r.value/1000),name:shortSeason(s),type:'scatter',mode:'lines+markers',marker:{size:s===ss.at(-1)?6:3},line:{width:s===ss.at(-1)?3:1.4,color:s===ss.at(-1)?'#d00000':colors[i%colors.length]},hovertemplate:`${shortSeason(s)} %{x}<br>%{y:,.0f}<extra></extra>`}})}
function timeline(m){const rr=[...m.rows].sort((a,b)=>+a.season.slice(0,4)-+b.season.slice(0,4)||byOrder(a,b));return[{x:rr.map(r=>shortSeason(r.season)+' '+r.period),y:rr.map(r=>r.value/1000),name:'产量',type:'scatter',mode:'lines+markers',line:{color:'#087f8c',width:2.5},hovertemplate:'%{x}<br>%{y:,.0f}<extra></extra>'},{x:rr.map(r=>shortSeason(r.season)+' '+r.period),y:rr.map(r=>r.yoy_pct),name:'同比',type:'scatter',mode:'lines',yaxis:'y2',line:{color:'#e8590c',width:1.8,dash:'dot'},hovertemplate:'同比 %{y:.1%}<extra></extra>'}]}
function layout(mode){return{margin:{l:62,r:58,t:32,b:58},paper_bgcolor:'#fff',plot_bgcolor:'#fff',hovermode:'x unified',legend:{orientation:'h',y:1.14,font:{size:10}},xaxis:{type:'category',rangeslider:{visible:mode==='timeline',thickness:.08},gridcolor:'#edf1f2',categoryorder:'array',categoryarray:mode==='timeline'?undefined:order,tickangle:-45},yaxis:{title:'百万升',gridcolor:'#edf1f2',tickformat:',.0f'},yaxis2:{title:'同比',overlaying:'y',side:'right',tickformat:'.0%',showgrid:false},font:{family:'Segoe UI,Microsoft YaHei',color:'#29495c',size:11}}}
const root=document.getElementById('chartSections');let ci=0;defs.forEach(group=>{const h=document.createElement('div');h.className='section-title';h.textContent=group.group;root.appendChild(h);const grid=document.createElement('div');grid.className='charts';root.appendChild(grid);group.items.forEach(([id,title])=>{const m=metricMap[id];if(!m)return;const i=ci++;const el=document.createElement('div');el.className='panel';el.innerHTML=`<h3>${title}（百万升）</h3><select class=mode><option value=concise>简明季节性图</option><option value=seasonal>各榨季季节性</option><option value=timeline>历史时间轴 + 同比</option></select><div id="c${i}" class=chart></div>`;grid.appendChild(el);const sel=el.querySelector('select');const draw=()=>{const tr=sel.value==='concise'?concise(m):sel.value==='seasonal'?seasonal(m):timeline(m);Plotly.react('c'+i,tr,layout(sel.value),{responsive:true,displaylogo:false})};sel.onchange=draw;draw()})});
const ms=document.getElementById('metricSel'),ps=document.getElementById('pageSel');DATA.metrics.sort((a,b)=>(titleMap[a.id]||a.name).localeCompare(titleMap[b.id]||b.name,'zh')).forEach(m=>{const o=document.createElement('option');o.value=m.id;o.textContent=titleMap[m.id]||m.name.replaceAll('Biweekly','双周').replaceAll('Accumulated','累计').replaceAll('Total','总量').replaceAll('Anhydrous','无水').replaceAll('Hydrous','含水').replaceAll('Corn','玉米').replaceAll('Cane','甘蔗').replaceAll('South-Central','中南部');ms.appendChild(o)});ms.value='south_central_total_biweekly';
function rebuildPages(){const m=metricMap[ms.value],available=order.filter(p=>m.rows.some(r=>r.period===p)),latestPeriod=latest(m).period;ps.innerHTML=available.map(p=>`<option value="${p}">同一节点 ${p}</option>`).join('');ps.value=available.includes(latestPeriod)?latestPeriod:available.at(-1)}
function drawDB(){const m=metricMap[ms.value],period=ps.value,all=[...m.rows].filter(r=>r.period===period).sort((a,b)=>+b.season.slice(0,4)-+a.season.slice(0,4)),rr=all;document.getElementById('table').innerHTML='<table><tr><th>榨季/节点</th><th>数值（百万升）</th><th>同比</th><th>分位</th><th>去趋势</th></tr>'+rr.map(r=>`<tr><td>${shortSeason(r.season)} ${r.period}</td><td>${fmtDb(r.value)}</td><td>${pct(r.yoy_pct)}</td><td>${pct(r.percentile)}</td><td>${pct(r.detrended_percentile)}</td></tr>`).join('')+'</table>';const asc=[...m.rows].filter(r=>r.period===period).sort((a,b)=>+a.season.slice(0,4)-+b.season.slice(0,4)),p=document.getElementById('pctSel').value;Plotly.react('dbchart',[{x:asc.map(r=>shortSeason(r.season)),y:asc.map(r=>r.value/1000),name:'数值（百万升）',mode:'lines',line:{color:'#087f8c'}},{x:asc.map(r=>shortSeason(r.season)),y:asc.map(r=>r[p]),name:p==='percentile'?'分位':'去趋势分位',yaxis:'y2',mode:'lines',line:{color:'#e8590c'}}],{...layout('timeline'),yaxis2:{title:'分位',overlaying:'y',side:'right',tickformat:'.0%',range:[0,1],showgrid:false}},{responsive:true,displaylogo:false})}ms.onchange=()=>{rebuildPages();drawDB()};ps.onchange=drawDB;document.getElementById('pctSel').onchange=drawDB;rebuildPages();drawDB();
document.getElementById('pdfBtn').onclick=()=>window.print();
}).catch(e=>{document.getElementById('status').textContent='UNICA 数据加载失败：'+e.message;console.error(e)});
